// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AutosaveProject silently writes a recovery snapshot. It never touches the
 * user's actual project file, so it can't clobber a deliberate save.
 */
export function AutosaveProject(project: $models.Project): $CancellablePromise<void> {
    return $Call.ByID(1427929080, project);
}

/**
 * ClearAutosave removes the recovery snapshot (after a successful explicit
 * save, or once the user has decided not to recover it).
 */
export function ClearAutosave(): $CancellablePromise<void> {
    return $Call.ByID(2629823112);
}

/**
 * ClearCurrentFilePath clears the current file path (for New Project)
 */
export function ClearCurrentFilePath(): $CancellablePromise<void> {
    return $Call.ByID(1509154294);
}

/**
 * CreateMarker creates a new marker with auto-generated ID and timestamp
 */
export function CreateMarker(lineID: string, position: number, label: string, color: string): $CancellablePromise<$models.Marker> {
    return $Call.ByID(4114540791, lineID, position, label, color);
}

/**
 * ExportHTML exports the compiled content to HTML format
 */
export function ExportHTML(sections: $models.CompiledSection[] | null): $CancellablePromise<string> {
    return $Call.ByID(1146085494, sections);
}

/**
 * ExportODT exports the compiled content to ODT format
 */
export function ExportODT(sections: $models.CompiledSection[] | null): $CancellablePromise<string> {
    return $Call.ByID(2307887988, sections);
}

/**
 * GetCurrentFilePath returns the current file path
 */
export function GetCurrentFilePath(): $CancellablePromise<string> {
    return $Call.ByID(1722469277);
}

/**
 * GetRecentProjects returns the list of recently opened projects
 */
export function GetRecentProjects(): $CancellablePromise<$models.RecentProject[] | null> {
    return $Call.ByID(2741556134);
}

/**
 * HasAutosave reports whether a recovery snapshot exists from a previous session.
 */
export function HasAutosave(): $CancellablePromise<boolean> {
    return $Call.ByID(2985110253);
}

/**
 * LoadAutosave reads the recovery snapshot, if any.
 */
export function LoadAutosave(): $CancellablePromise<$models.AutosaveEnvelope | null> {
    return $Call.ByID(3231201959);
}

/**
 * LoadProject loads a project from a file
 */
export function LoadProject(): $CancellablePromise<$models.Project | null> {
    return $Call.ByID(2543493242);
}

/**
 * LoadProjectFromPath loads a project from a specific path
 */
export function LoadProjectFromPath(filePath: string): $CancellablePromise<$models.Project | null> {
    return $Call.ByID(4243148661, filePath);
}

/**
 * NewProject creates a new empty project
 */
export function NewProject(): $CancellablePromise<$models.Project> {
    return $Call.ByID(1512927538);
}

/**
 * QuitApp terminates the application (called from frontend after confirmation)
 */
export function QuitApp(): $CancellablePromise<void> {
    return $Call.ByID(3730234565);
}

/**
 * SaveProject saves a project to a file
 */
export function SaveProject(project: $models.Project): $CancellablePromise<string> {
    return $Call.ByID(1642150229, project);
}

/**
 * SaveProjectAs saves a project to a new file location
 */
export function SaveProjectAs(project: $models.Project): $CancellablePromise<string> {
    return $Call.ByID(2008761757, project);
}

/**
 * UpdateMarker updates an existing marker's fields
 */
export function UpdateMarker(id: string, label: string, content: string, tags: string[] | null, category: string, color: string): $CancellablePromise<$models.Marker> {
    return $Call.ByID(1834029478, id, label, content, tags, category, color);
}
