// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AutosaveEnvelope wraps a project snapshot with when it was autosaved,
 * so a recovery prompt can tell the user how stale it is.
 */
export interface AutosaveEnvelope {
    "project": Project;
    "savedAt": string;
}

/**
 * CompiledSection represents a section for export
 */
export interface CompiledSection {
    "label": string;
    "content": string;
    "color": string;
    "category": string;
    "tags": string[] | null;
}

/**
 * Config represents editor configuration
 */
export interface Config {
    "horizontalLines": number;
    "verticalLines": number;
    "showHorizontal": boolean;
    "showVertical": boolean;
    "backgroundColor": string;
    "snapThreshold": number;
    "canvasPadding": number;
}

/**
 * Marker represents a marker on the timeline
 */
export interface Marker {
    "id": string;
    "lineId": string;
    "crossLineId"?: string;
    "position": number;
    "label": string;
    "content": string;
    "tags": string[] | null;
    "category": string;
    "color": string;
    "linkedMarkerIds"?: string[] | null;
    "writingStatus"?: string;
    "createdAt": string;
    "updatedAt": string;
}

export interface NarrativePath {
    "id": string;
    "name": string;
    "markerIds": string[] | null;
}

/**
 * Project represents a saved project state
 */
export interface Project {
    "id": string;
    "name": string;
    "config": Config;
    "markers": Marker[] | null;
    "compileSlots": string[] | null;
    "narrativePaths"?: NarrativePath[] | null;
    "activeNarrativePathId"?: string;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * RecentProject represents a recently opened project
 */
export interface RecentProject {
    "path": string;
    "name": string;
    "openedAt": string;
}
