// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearCurrentFilePath():Promise<void>;

export function CreateMarker(arg1:string,arg2:number,arg3:string,arg4:string):Promise<main.Marker>;

export function ExportHTML(arg1:Array<main.CompiledSection>):Promise<string>;

export function ExportODT(arg1:Array<main.CompiledSection>):Promise<string>;

export function GetCurrentFilePath():Promise<string>;

export function GetRecentProjects():Promise<Array<main.RecentProject>>;

export function LoadProject():Promise<main.Project>;

export function LoadProjectFromPath(arg1:string):Promise<main.Project>;

export function NewProject():Promise<main.Project>;

export function QuitApp():Promise<void>;

export function SaveProject(arg1:main.Project):Promise<string>;

export function SaveProjectAs(arg1:main.Project):Promise<string>;

export function UpdateMarker(arg1:string,arg2:string,arg3:string,arg4:Array<string>,arg5:string,arg6:string):Promise<main.Marker>;
