// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearCurrentFilePath() {
  return window['go']['main']['App']['ClearCurrentFilePath']();
}

export function CreateMarker(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateMarker'](arg1, arg2, arg3, arg4);
}

export function ExportHTML(arg1) {
  return window['go']['main']['App']['ExportHTML'](arg1);
}

export function ExportODT(arg1) {
  return window['go']['main']['App']['ExportODT'](arg1);
}

export function GetCurrentFilePath() {
  return window['go']['main']['App']['GetCurrentFilePath']();
}

export function GetRecentProjects() {
  return window['go']['main']['App']['GetRecentProjects']();
}

export function LoadProject() {
  return window['go']['main']['App']['LoadProject']();
}

export function LoadProjectFromPath(arg1) {
  return window['go']['main']['App']['LoadProjectFromPath'](arg1);
}

export function NewProject() {
  return window['go']['main']['App']['NewProject']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function SaveProject(arg1) {
  return window['go']['main']['App']['SaveProject'](arg1);
}

export function SaveProjectAs(arg1) {
  return window['go']['main']['App']['SaveProjectAs'](arg1);
}

export function UpdateMarker(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateMarker'](arg1, arg2, arg3, arg4, arg5, arg6);
}
